# Generated by `hz shell fish`.

function hz
    if test (count $argv) -eq 0
        command hz
        return
    end

    set cmd $argv[1]
    switch $cmd
        case new
            for arg in $argv
                switch $arg
                    case --json --path-only --help -h
                        command hz $argv
                        return
                end
            end

            set hz_target_path (command hz $argv --path-only)
            or return
            builtin cd "$hz_target_path"
        case cd
            set rest $argv[2..-1]
            for arg in $rest
                switch $arg
                    case --json --path-only --help -h
                        command hz $cmd $rest
                        return
                end
            end

            set hz_target_path (command hz path $rest)
            or return
            builtin cd "$hz_target_path"
        case '*'
            command hz $argv
    end
end

function hzcd
    hz cd $argv
end

function hzlocal
    hz cd local $argv
end
