# Generated by `hz shell zsh`.

alias hz='noglob _hz'
alias hzcd='noglob _hzcd'
alias hzroot='noglob _hzroot'

_hz() {
  if [[ "$#" -eq 0 ]]; then command hz; return; fi
  local cmd="$1" navigate=0
  case "$cmd" in
    init|new|remove|rm|restore|cd) navigate=1 ;;
    git) [[ "${2-}" == "handoff" ]] && navigate=1 ;;
  esac
  if [[ "$navigate" -eq 1 ]]; then
    local arg
    for arg in "$@"; do
      case "$arg" in
        --) break ;;
        --json|--machine|--path-only|--help|-h|-j) command hz "$@"; return ;;
      esac
    done
    local hz_target_path
    if [[ "$cmd" == "cd" ]]; then
      shift
      hz_target_path="$(command hz path "$@")" || return
    else
      local -a hz_args=()
      local inserted=0
      for arg in "$@"; do
        if [[ "$inserted" -eq 0 && "$arg" == "--" ]]; then
          hz_args+=(--path-only)
          inserted=1
        fi
        hz_args+=("$arg")
      done
      if [[ "$inserted" -eq 0 ]]; then hz_args+=(--path-only); fi
      hz_target_path="$(command hz "${hz_args[@]}")" || return
    fi
    [[ -n "$hz_target_path" ]] && builtin cd -- "$hz_target_path"
    return
  fi
  command hz "$@"
}

_hzcd() { _hz cd "$@"; }
_hzroot() { _hz cd root "$@"; }

_hz_completion_context() {
  local index at=""
  reply=()
  for (( index=2; index < CURRENT; index++ )); do
    case "${words[index]}" in
      --) break ;;
      -a|--at)
        if (( index + 1 < CURRENT )); then
          at="${words[index + 1]}"
          (( index++ ))
        fi
        ;;
      --at=*) at="${words[index]#--at=}" ;;
      -a=*) at="${words[index]#-a=}" ;;
      -a?*) at="${words[index]#-a}" ;;
    esac
  done
  [[ -n "$at" ]] && reply=(--at "$at")
}

_hz_targets() {
  local -a targets context
  _hz_completion_context
  context=("${reply[@]}")
  targets=("${(@f)$(command hz __complete workspace-targets "${context[@]}" 2>/dev/null)}")
  compadd -a targets
}

_hz_trash_targets() {
  local -a targets context
  _hz_completion_context
  context=("${reply[@]}")
  targets=("${(@f)$(command hz __complete trash-targets "${context[@]}" 2>/dev/null)}")
  compadd -a targets
}

_hz_complete() {
  local state command="" subcommand="" index
  _arguments -C \
    '--machine[emit stable machine-readable output]' \
    '1:command:(init new path cd list ls pwd ancestors remove rm pin unpin restore gc adopt doctor git hg config install shell update)' \
    '*::arg:->args'

  # Global options may precede the command, so positional word indexes are not
  # stable. Find the first non-global word and, for command groups, the next.
  for (( index=2; index < CURRENT; index++ )); do
    case "${words[index]}" in
      --machine|-h|--help|-V|--version) ;;
      *) command="${words[index]}"; break ;;
    esac
  done
  if [[ "$command" == "git" || "$command" == "hg" || "$command" == "config" ]]; then
    for (( index++; index < CURRENT; index++ )); do
      case "${words[index]}" in
        --machine|-h|--help|-V|--version) ;;
        *) subcommand="${words[index]}"; break ;;
      esac
    done
  fi

  case "$command" in
    path|cd|ancestors|remove|rm|pin|unpin) _hz_targets ;;
    restore) _hz_trash_targets ;;
    git)
      case "$subcommand" in
        status|handoff) _hz_targets ;;
        *) _values 'git command' status handoff ;;
      esac
      ;;
    hg)
      case "$subcommand" in
        status) _hz_targets ;;
        *) _values 'hg command' status ;;
      esac
      ;;
    config) _values 'config command' init ;;
  esac
}
if (( ! $+functions[compdef] )); then
  autoload -Uz compinit && compinit
fi
if (( $+functions[compdef] )); then
  compdef _hz_complete hz _hz
fi
