# Generated by `hz shell zsh`.

hz() {
  if [[ "$#" -eq 0 ]]; then
    command hz
    return
  fi

  local cmd="$1"
  case "$cmd" in
    new)
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--path-only|--help|-h)
            command hz "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz "$@" --path-only)" || return
      builtin cd "$hz_target_path"
      ;;
    cd)
      shift
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--path-only|--help|-h)
            command hz "$cmd" "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz path "$@")" || return
      builtin cd "$hz_target_path"
      ;;
    *)
      command hz "$@"
      ;;
  esac
}

hzcd() {
  hz cd "$@"
}

hzlocal() {
  hz cd local "$@"
}
