# Generated by `hz shell bash`.

hz() {
  if [[ "$#" -eq 0 ]]; then command hz; return; fi
  local cmd="$1"
  local navigate=0
  case "$cmd" in
    init|new|remove|rm|restore) navigate=1 ;;
    cd) navigate=1 ;;
    git) [[ "${2-}" == "handoff" ]] && navigate=1 ;;
  esac
  if [[ "$navigate" -eq 1 ]]; then
    local arg
    for arg in "$@"; do
      case "$arg" in
        --) break ;;
        --json|--machine|--path-only|--help|-h|-j) command hz "$@"; return ;;
      esac
    done
    local path
    if [[ "$cmd" == "cd" ]]; then
      shift
      path="$(command hz path "$@")" || return
    else
      local -a hz_args=()
      local inserted=0
      for arg in "$@"; do
        if [[ "$inserted" -eq 0 && "$arg" == "--" ]]; then
          hz_args+=(--path-only)
          inserted=1
        fi
        hz_args+=("$arg")
      done
      if [[ "$inserted" -eq 0 ]]; then hz_args+=(--path-only); fi
      path="$(command hz "${hz_args[@]}")" || return
    fi
    [[ -n "$path" ]] && builtin cd -- "$path"
    return
  fi
  command hz "$@"
}

hzcd() { hz cd "$@"; }
hzroot() { hz cd root "$@"; }

_hz_target_completions() {
  local kind="$1" current="$2" at="" word
  local index
  for (( index=2; index < COMP_CWORD; index++ )); do
    word="${COMP_WORDS[index]}"
    case "$word" in
      --) break ;;
      -a|--at)
        if (( index + 1 < COMP_CWORD )); then
          at="${COMP_WORDS[index + 1]}"
          (( index++ ))
        fi
        ;;
      --at=*) at="${word#--at=}" ;;
      -a=*) at="${word#-a=}" ;;
      -a?*) at="${word#-a}" ;;
    esac
  done
  local -a context=()
  [[ -n "$at" ]] && context=(--at "$at")
  COMPREPLY=()
  local target
  while IFS= read -r target; do
    [[ "$target" == "$current"* ]] && COMPREPLY+=("$target")
  done < <(command hz __complete "$kind" "${context[@]}" 2>/dev/null)
}

_hz_complete() {
  local current="${COMP_WORDS[COMP_CWORD]}"
  local top="init new path cd list ls pwd ancestors remove rm pin unpin restore gc adopt doctor git hg config install shell update"
  local command="" subcommand="" command_index=0 index word
  COMPREPLY=()

  # Global options may precede the command, so find the first non-global word.
  for (( index=1; index < COMP_CWORD; index++ )); do
    word="${COMP_WORDS[index]}"
    case "$word" in
      --machine|-h|--help|-V|--version) continue ;;
    esac
    command="$word"
    command_index="$index"
    break
  done
  if [[ -z "$command" ]]; then
    COMPREPLY=( $(compgen -W "$top" -- "$current") )
    return
  fi

  # Group commands can likewise have a global option before their subcommand.
  for (( index=command_index + 1; index < COMP_CWORD; index++ )); do
    word="${COMP_WORDS[index]}"
    case "$word" in
      --machine|-h|--help|-V|--version) continue ;;
    esac
    subcommand="$word"
    break
  done

  case "$command" in
    git)
      if [[ -z "$subcommand" ]]; then
        COMPREPLY=( $(compgen -W "status handoff" -- "$current") )
      else
        case "$subcommand" in
          status|handoff) _hz_target_completions workspace-targets "$current" ;;
        esac
      fi
      ;;
    hg)
      if [[ -z "$subcommand" ]]; then
        COMPREPLY=( $(compgen -W "status" -- "$current") )
      elif [[ "$subcommand" == "status" ]]; then
        _hz_target_completions workspace-targets "$current"
      fi
      ;;
    config)
      [[ -z "$subcommand" ]] && COMPREPLY=( $(compgen -W "init" -- "$current") )
      ;;
    path|cd|ancestors|remove|rm|pin|unpin)
      _hz_target_completions workspace-targets "$current"
      ;;
    restore)
      _hz_target_completions trash-targets "$current"
      ;;
  esac
}
complete -F _hz_complete hz
