# Generated by `hz shell fish`.

function hz
    if test (count $argv) -eq 0
        command hz
        return
    end
    set -l cmd $argv[1]
    set -l navigate 0
    switch $cmd
        case init new remove rm restore cd
            set navigate 1
        case git
            test (count $argv) -ge 2; and test "$argv[2]" = handoff; and set navigate 1
    end
    if test $navigate -eq 1
        for arg in $argv
            if test "$arg" = --
                break
            end
            switch $arg
                case --json --machine --path-only --help -h -j
                    command hz $argv
                    return
            end
        end
        if test "$cmd" = cd
            set -e argv[1]
            set -l path (command hz path $argv); or return
            builtin cd "$path"
        else
            set -l hz_args
            set -l inserted 0
            for arg in $argv
                if test $inserted -eq 0; and test "$arg" = --
                    set -a hz_args --path-only
                    set inserted 1
                end
                set -a hz_args "$arg"
            end
            if test $inserted -eq 0
                set -a hz_args --path-only
            end
            set -l path (command hz $hz_args); or return
            builtin cd "$path"
        end
        return
    end
    command hz $argv
end

function hzcd
    hz cd $argv
end
function hzroot
    hz cd root $argv
end

function __hz_complete_targets
    set -l kind $argv[1]
    set -l tokens (commandline -opc)
    set -l at
    set -l index 2
    while test $index -le (count $tokens)
        set -l token $tokens[$index]
        switch $token
            case --
                break
            case -a --at
                set index (math $index + 1)
                if test $index -le (count $tokens)
                    set at $tokens[$index]
                end
            case '--at=*'
                set at (string replace -- '--at=' '' $token)
            case '-a=*'
                set at (string replace -- '-a=' '' $token)
            case '-a?*'
                set at (string sub --start 3 $token)
        end
        set index (math $index + 1)
    end
    if test -n "$at"
        command hz __complete $kind --at "$at" 2>/dev/null
    else
        command hz __complete $kind 2>/dev/null
    end
end

function __hz_targets
    __hz_complete_targets workspace-targets
end
function __hz_trash_targets
    __hz_complete_targets trash-targets
end

# Return command words after removing global options, whose positions are not
# fixed because clap accepts them before or after subcommands.
function __hz_command_tokens
    set -l tokens (commandline -opc)
    set -l index 2
    while test $index -le (count $tokens)
        set -l token $tokens[$index]
        if not contains -- "$token" --machine -h --help -V --version
            printf '%s\n' "$token"
        end
        set index (math $index + 1)
    end
end

function __hz_top_level_is
    set -l command_tokens (__hz_command_tokens)
    test (count $command_tokens) -ge 1; and contains -- "$command_tokens[1]" $argv
end

function __hz_git_needs_subcommand
    set -l command_tokens (__hz_command_tokens)
    test (count $command_tokens) -eq 1; and test "$command_tokens[1]" = git
end

function __hz_git_needs_target
    set -l command_tokens (__hz_command_tokens)
    test (count $command_tokens) -ge 2; and test "$command_tokens[1]" = git; and contains -- "$command_tokens[2]" status handoff
end

function __hz_hg_needs_subcommand
    set -l command_tokens (__hz_command_tokens)
    test (count $command_tokens) -eq 1; and test "$command_tokens[1]" = hg
end

function __hz_hg_needs_target
    set -l command_tokens (__hz_command_tokens)
    test (count $command_tokens) -ge 2; and test "$command_tokens[1]" = hg; and test "$command_tokens[2]" = status
end

function __hz_config_needs_subcommand
    set -l command_tokens (__hz_command_tokens)
    test (count $command_tokens) -eq 1; and test "$command_tokens[1]" = config
end

complete -c hz -e
complete -c hz -f
complete -c hz -n 'not __fish_seen_subcommand_from init new path cd list ls pwd ancestors remove rm pin unpin restore gc adopt doctor git hg config install shell update' -a 'init new path cd list ls pwd ancestors remove rm pin unpin restore gc adopt doctor git hg config install shell update'
complete -c hz -n '__hz_top_level_is path cd ancestors remove rm pin unpin' -a '(__hz_targets)'
complete -c hz -n '__hz_top_level_is restore' -a '(__hz_trash_targets)'
complete -c hz -n '__hz_git_needs_subcommand' -a 'status handoff'
complete -c hz -n '__hz_git_needs_target' -a '(__hz_targets)'
complete -c hz -n '__hz_hg_needs_subcommand' -a status
complete -c hz -n '__hz_hg_needs_target' -a '(__hz_targets)'
complete -c hz -n '__hz_config_needs_subcommand' -a init
