[package]
name = "hz-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
dirs.workspace = true
fs2.workspace = true
getrandom.workspace = true
hz-core.workspace = true
libc.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
ulid.workspace = true
walkdir.workspace = true

[target.'cfg(windows)'.dependencies]
winapi-util.workspace = true

[dev-dependencies]
tempfile.workspace = true
