# Generated by `hz shell bash`.

hz() {
  if [[ "$#" -eq 0 ]]; then
    command hz
    return
  fi

  local cmd="$1"
  case "$cmd" in
    new|fork)
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--machine|--path-only|--help|-h|-j)
            command hz "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz "$@" --path-only)" || return
      builtin cd "$hz_target_path" || return
      ;;
    handoff)
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--machine|--path-only|--help|-h|-j)
            command hz "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz "$@" --path-only)" || return
      builtin cd "$hz_target_path" || return
      ;;
    cd)
      shift
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--machine|--path-only|--help|-h|-j)
            command hz "$cmd" "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz path "$@")" || return
      builtin cd "$hz_target_path" || return
      ;;
    *)
      command hz "$@"
      ;;
  esac
}

hzcd() {
  hz cd "$@"
}

hzlocal() {
  hz cd local "$@"
}

_hz_top_commands="new fork path cd list ls pwd remove rm handoff init install setup cleanup shell update worktree wt"
_hz_worktree_commands="new fork path cd list ls pwd remove rm handoff"
_hz_agent_commands="new fork path cd list ls pwd current remove rm handoff setup cleanup"
_hz_shells="zsh bash fish"

_hz_reply() {
  local candidates="$1"
  local current="$2"
  COMPREPLY+=( $(compgen -W "$candidates" -- "$current") )
}

_hz_dynamic_reply() {
  local command="$1"
  local current="$2"
  local candidates repo
  repo="$(_hz_repo_arg)"
  if [[ -n "$repo" ]]; then
    candidates="$(command hz __complete "$command" -r "$repo" 2>/dev/null)" || return
  else
    candidates="$(command hz __complete "$command" 2>/dev/null)" || return
  fi
  _hz_reply "$candidates" "$current"
}

_hz_complete_files() {
  local current="$1"
  COMPREPLY+=( $(compgen -f -- "$current") )
}

_hz_complete_dirs() {
  local current="$1"
  COMPREPLY+=( $(compgen -d -- "$current") )
}

_hz_repo_arg() {
  local index word
  for ((index = 1; index < COMP_CWORD; index++)); do
    word="${COMP_WORDS[index]}"
    case "$word" in
      -r|--repo)
        if ((index + 1 < COMP_CWORD)); then
          printf '%s' "${COMP_WORDS[index+1]}"
          return
        fi
        ;;
      --repo=*)
        printf '%s' "${word#--repo=}"
        return
        ;;
    esac
  done
}

_hz_git_refs() {
  local repo
  repo="$(_hz_repo_arg)"
  if [[ -n "$repo" ]]; then
    command git -C "$repo" for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null
  else
    command git for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null
  fi
}

_hz_git_ref_reply() {
  local current="$1"
  local candidates
  candidates="$(_hz_git_refs)" || return
  _hz_reply "$candidates" "$current"
}

_hz_complete_option_value() {
  local cmd="$1"
  local current="${COMP_WORDS[COMP_CWORD]}"
  local previous="${COMP_WORDS[COMP_CWORD-1]}"

  case "$previous" in
    -r|--repo)
      case "$cmd" in
        new|fork|path|cd|list|ls|pwd|current|remove|rm|handoff|setup|cleanup|init)
          _hz_complete_dirs "$current"
          return 0
          ;;
      esac
      ;;
    -p|--path)
      if [[ "$cmd" == "new" || "$cmd" == "fork" ]]; then
        _hz_complete_dirs "$current"
        return 0
      fi
      ;;
    --install-dir)
      if [[ "$cmd" == "update" ]]; then
        _hz_complete_dirs "$current"
        return 0
      fi
      ;;
    -B)
      case "$cmd" in
        new)
          _hz_git_ref_reply "$current"
          return 0
          ;;
      esac
      ;;
    -b)
      case "$cmd" in
        new)
          _hz_git_ref_reply "$current"
          return 0
          ;;
      esac
      ;;
    --base)
      case "$cmd" in
        new)
          _hz_git_ref_reply "$current"
          return 0
          ;;
      esac
      ;;
    --branch)
      case "$cmd" in
        new)
          _hz_git_ref_reply "$current"
          return 0
          ;;
      esac
      ;;
    --target-version)
      [[ "$cmd" == "update" ]] && return 0
      ;;
    --max-detached)
      case "$cmd" in
        new|fork|handoff)
          return 0
          ;;
      esac
      ;;
    --max-branch-worktrees)
      case "$cmd" in
        new|handoff)
          return 0
          ;;
      esac
      ;;
  esac

  return 1
}

_hz_complete_command_args() {
  local cmd="$1"
  local current="$2"

  if _hz_complete_option_value "$cmd"; then
    return
  fi

  case "$cmd" in
    new)
      [[ "$current" == -* ]] && _hz_reply "-r --repo -p --path -B --base -b --branch --max-detached --max-branch-worktrees -j --json -d --debug --setup --no-setup --machine -h --help" "$current"
      ;;
    fork)
      [[ "$current" == -* ]] && _hz_reply "-r --repo -p --path --no-diff --max-detached -j --json --machine -h --help" "$current"
      ;;
    path|cd)
      if [[ "$current" == -* ]]; then
        _hz_reply "-r --repo -j --json --machine -h --help" "$current"
      else
        _hz_dynamic_reply worktree-targets "$current"
      fi
      ;;
    list|ls)
      [[ "$current" == -* ]] && _hz_reply "-r --repo -j --json --machine -h --help" "$current"
      ;;
    pwd|current)
      [[ "$current" == -* ]] && _hz_reply "-r --repo -j --json --machine -h --help" "$current"
      ;;
    remove|rm)
      if [[ "$current" == -* ]]; then
        _hz_reply "-r --repo -j --json -f --force --yes -d --debug --cleanup --no-cleanup --machine -h --help" "$current"
      else
        _hz_dynamic_reply removable-worktrees "$current"
      fi
      ;;
    handoff)
      if [[ "$current" == -* ]]; then
        _hz_reply "-b --branch -n --new --max-detached --max-branch-worktrees -r --repo -j --json --machine -h --help" "$current"
      else
        _hz_dynamic_reply worktree-targets "$current"
      fi
      ;;
    setup|cleanup)
      if [[ "$current" == -* ]]; then
        _hz_reply "-r --repo -j --json --machine -h --help" "$current"
      else
        _hz_dynamic_reply worktree-targets "$current"
      fi
      ;;
    init)
      if [[ "$current" == -* ]]; then
        _hz_reply "-r --repo --machine -h --help" "$current"
      else
        _hz_reply "$_hz_shells" "$current"
      fi
      ;;
    install|shell)
      if [[ "$current" == -* ]]; then
        _hz_reply "--machine -h --help" "$current"
      else
        _hz_reply "$_hz_shells" "$current"
      fi
      ;;
    update)
      [[ "$current" == -* ]] && _hz_reply "--target-version --install-dir --machine -h --help" "$current"
      ;;
  esac
}


_hz_completion() {
  local current="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=()

  if [[ "$COMP_CWORD" -eq 1 ]]; then
    if [[ "$current" == -* ]]; then
      _hz_reply "--machine -h --help -V --version" "$current"
    else
      _hz_reply "$_hz_top_commands" "$current"
    fi
    return
  fi

  local cmd="${COMP_WORDS[1]}"
  if [[ "$cmd" == "worktree" || "$cmd" == "wt" || "$cmd" == "agent" ]]; then
    if [[ "$COMP_CWORD" -eq 2 ]]; then
      if [[ "$current" == -* ]]; then
        _hz_reply "--machine -h --help" "$current"
      elif [[ "$cmd" == "agent" ]]; then
        _hz_reply "$_hz_agent_commands" "$current"
      else
        _hz_reply "$_hz_worktree_commands" "$current"
      fi
      return
    fi
    _hz_complete_command_args "${COMP_WORDS[2]}" "$current"
    return
  fi


  _hz_complete_command_args "$cmd" "$current"
}

_hzcd_completion() {
  local current="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=()

  if _hz_complete_option_value cd; then
    return
  fi

  if [[ "$current" == -* ]]; then
    _hz_reply "-r --repo -j --json --machine -h --help" "$current"
  else
    _hz_dynamic_reply worktree-targets "$current"
  fi
}

_hzlocal_completion() {
  local current="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=()

  if _hz_complete_option_value cd; then
    return
  fi

  [[ "$current" == -* ]] && _hz_reply "-r --repo -j --json --machine -h --help" "$current"
}

complete -F _hz_completion hz
complete -F _hzcd_completion hzcd
complete -F _hzlocal_completion hzlocal
