# Generated by `hz shell fish`.

function hz
    if test (count $argv) -eq 0
        command hz
        return
    end

    set cmd $argv[1]
    switch $cmd
        case new fork
            for arg in $argv
                switch $arg
                    case --json --machine --path-only --help -h -j
                        command hz $argv
                        return
                end
            end

            set hz_target_path (command hz $argv --path-only)
            or return
            builtin cd "$hz_target_path"
            or return
        case handoff
            for arg in $argv
                switch $arg
                    case --json --machine --path-only --help -h -j
                        command hz $argv
                        return
                end
            end

            set hz_target_path (command hz $argv --path-only)
            or return
            builtin cd "$hz_target_path"
            or return
        case cd
            set rest $argv[2..-1]
            for arg in $rest
                switch $arg
                    case --json --machine --path-only --help -h -j
                        command hz $cmd $rest
                        return
                end
            end

            set hz_target_path (command hz path $rest)
            or return
            builtin cd "$hz_target_path"
            or return
        case '*'
            command hz $argv
    end
end

function hzcd
    hz cd $argv
end

function hzlocal
    hz cd local $argv
end

function __hz_complete_worktree_targets
    set -l repo (__hz_current_repo_arg)
    if test -n "$repo"
        command hz __complete worktree-targets -r "$repo" 2>/dev/null
    else
        command hz __complete worktree-targets 2>/dev/null
    end
end

function __hz_complete_removable_worktrees
    set -l repo (__hz_current_repo_arg)
    if test -n "$repo"
        command hz __complete removable-worktrees -r "$repo" 2>/dev/null
    else
        command hz __complete removable-worktrees 2>/dev/null
    end
end

function __hz_needs_worktree_subcommand
    set -l cmd (__hz_command_token)
    contains -- "$cmd" worktree wt; or return 1
    set -l subcmd_index (__hz_subcommand_index)
    test -z "$subcmd_index"
end

function __hz_needs_agent_subcommand
    set -l cmd (__hz_command_token)
    test "$cmd" = agent; or return 1
    set -l subcmd_index (__hz_subcommand_index)
    test -z "$subcmd_index"
end

function __hz_is_global_flag
    contains -- "$argv[1]" --machine -h --help -V --version
end

function __hz_completed_token_count
    set -l tokens (commandline -opc)
    set -l current (commandline -ct)
    set -l count (count $tokens)
    test $count -gt 0; or return 1

    if test "$tokens[$count]" = "$current"
        set count (math $count - 1)
    end

    echo $count
end

function __hz_command_index
    set -l tokens (commandline -opc)
    set -l count (__hz_completed_token_count)
    test -n "$count"; or return 1
    test $count -ge 2; or return 1

    for index in (seq 2 $count)
        if __hz_is_global_flag "$tokens[$index]"
            continue
        end
        echo $index
        return 0
    end
    return 1
end

function __hz_command_token
    set -l tokens (commandline -opc)
    set -l index (__hz_command_index)
    test -n "$index"; or return 1
    echo $tokens[$index]
end

function __hz_subcommand_index
    set -l tokens (commandline -opc)
    set -l count (__hz_completed_token_count)
    set -l command_index (__hz_command_index)
    test -n "$count"; or return 1
    test -n "$command_index"; or return 1

    set -l start (math $command_index + 1)
    test $start -le $count; or return 1

    for index in (seq $start $count)
        if __hz_is_global_flag "$tokens[$index]"
            continue
        end
        echo $index
        return 0
    end
    return 1
end

function __hz_subcommand_token
    set -l tokens (commandline -opc)
    set -l index (__hz_subcommand_index)
    test -n "$index"; or return 1
    echo $tokens[$index]
end

function __hz_top_command_is
    set -l cmd (__hz_command_token)
    contains -- "$cmd" $argv
end

function __hz_command_is
    set -l cmd (__hz_command_token)
    test -n "$cmd"; or return 1
    if contains -- $cmd worktree wt agent
        set cmd (__hz_subcommand_token)
        test -n "$cmd"; or return 1
    end

    contains -- $cmd $argv
end



function __hz_current_repo_arg
    set -l tokens (commandline -opc)
    set -l count (count $tokens)
    test $count -gt 0; or return

    for index in (seq 1 $count)
        switch $tokens[$index]
            case -r --repo
                set -l next_index (math $index + 1)
                if test $next_index -le $count
                    echo $tokens[$next_index]
                    return
                end
            case '--repo=*'
                string replace -- '--repo=' '' $tokens[$index]
                return
        end
    end
end

function __hz_complete_git_refs
    set -l repo (__hz_current_repo_arg)
    if test -n "$repo"
        command git -C "$repo" for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null
    else
        command git for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null
    end
end

function __hz_previous_token
    set -l tokens (commandline -opc)
    set -l current (commandline -ct)
    set -l count (count $tokens)
    test $count -gt 0; or return

    if test "$tokens[$count]" = "$current"
        set count (math $count - 1)
    end
    test $count -gt 0; and echo $tokens[$count]
end

complete -c hz -e
complete -c hzcd -e
complete -c hzlocal -e

complete -c hz -f
complete -c hz -n "not __fish_seen_subcommand_from new fork path cd list ls pwd remove rm pin unpin handoff init install setup cleanup shell update worktree wt agent" -a "new fork path cd list ls pwd remove rm pin unpin handoff init install setup cleanup shell update worktree wt"
complete -c hz -n "__hz_needs_worktree_subcommand" -a "new fork path cd list ls pwd remove rm pin unpin handoff"
complete -c hz -n "__hz_needs_agent_subcommand" -a "new fork path cd list ls pwd current remove rm pin unpin handoff setup cleanup"

complete -c hz -n "__hz_command_is cd path handoff setup cleanup" -a "(__hz_complete_worktree_targets)"
complete -c hz -n "__hz_command_is rm remove pin unpin" -a "(__hz_complete_removable_worktrees)"
complete -c hz -n "__hz_top_command_is init install shell" -a "zsh bash fish"
complete -c hz -n "__hz_command_is new fork path cd list ls pwd current remove rm pin unpin handoff init setup cleanup" -s r -l repo -r -F
complete -c hz -n "__hz_command_is new fork" -s p -l path -r -F
complete -c hz -n "__hz_command_is new" -s B -l base -r -a "(__hz_complete_git_refs)"
complete -c hz -n "__hz_command_is new" -s b -l branch -r -a "(__hz_complete_git_refs)"
complete -c hz -n "__hz_command_is new fork handoff" -l max-detached -r
complete -c hz -n "__hz_command_is new handoff" -l max-branch-worktrees -r
complete -c hz -n "__hz_command_is new" -l no-setup
complete -c hz -n "__hz_command_is new" -l setup
complete -c hz -n "__hz_command_is fork" -l no-diff
complete -c hz -n "__hz_command_is list ls" -l pinned
complete -c hz -n "__hz_command_is list ls" -l unpinned
complete -c hz -n "__hz_command_is new fork path cd list ls pwd current remove rm pin unpin handoff setup cleanup" -s j -l json
complete -c hz -n "__hz_command_is new remove rm" -s d -l debug
complete -c hz -n "__hz_command_is remove rm" -s f -l force
complete -c hz -n "__hz_command_is remove rm" -l yes
complete -c hz -n "__hz_command_is remove rm" -l no-cleanup
complete -c hz -n "__hz_command_is remove rm" -l cleanup
complete -c hz -n "__hz_command_is handoff" -s b -l branch
complete -c hz -n "__hz_command_is handoff" -s n -l new
complete -c hz -n "__hz_top_command_is update" -l target-version -r
complete -c hz -n "__hz_top_command_is update" -l install-dir -r -F
complete -c hz -l machine
complete -c hz -s h -l help

complete -c hzcd -f
complete -c hzcd -a "(__hz_complete_worktree_targets)"
complete -c hzcd -s r -l repo -r -F
complete -c hzcd -s j -l json
complete -c hzcd -s h -l help

complete -c hzlocal -f
complete -c hzlocal -s r -l repo -r -F
complete -c hzlocal -s j -l json
complete -c hzlocal -s h -l help
complete -c hz -n "not __fish_seen_subcommand_from new fork path cd list ls pwd remove rm pin unpin handoff init install setup cleanup shell update worktree wt" -s V -l version
