# Generated by `hz shell fish`.

function hz
    if test (count $argv) -eq 0
        command hz
        return
    end

    set cmd $argv[1]
    switch $cmd
        case new fork
            for arg in $argv
                switch $arg
                    case --json --path-only --help -h -j
                        command hz $argv
                        return
                end
            end

            set hz_target_path (command hz $argv --path-only)
            or return
            builtin cd "$hz_target_path"
            or return
        case handoff
            for arg in $argv
                switch $arg
                    case --json --path-only --help -h -j
                        command hz $argv
                        return
                end
            end

            set hz_target_path (command hz $argv --path-only)
            or return
            builtin cd "$hz_target_path"
            or return
        case cd
            set rest $argv[2..-1]
            for arg in $rest
                switch $arg
                    case --json --path-only --help -h -j
                        command hz $cmd $rest
                        return
                end
            end

            set hz_target_path (command hz path $rest)
            or return
            builtin cd "$hz_target_path"
            or return
        case '*'
            command hz $argv
    end
end

function hzcd
    hz cd $argv
end

function hzlocal
    hz cd local $argv
end

function __hz_complete_worktree_targets
    set -l repo (__hz_current_repo_arg)
    if test -n "$repo"
        command hz __complete worktree-targets -r "$repo" 2>/dev/null
    else
        command hz __complete worktree-targets 2>/dev/null
    end
end

function __hz_complete_removable_worktrees
    set -l repo (__hz_current_repo_arg)
    if test -n "$repo"
        command hz __complete removable-worktrees -r "$repo" 2>/dev/null
    else
        command hz __complete removable-worktrees 2>/dev/null
    end
end

function __hz_needs_worktree_subcommand
    set -l tokens (commandline -opc)
    test (count $tokens) -ge 2; or return 1
    contains -- $tokens[2] worktree wt; or return 1

    if test (count $tokens) -eq 2
        return 0
    end

    set -l current (commandline -ct)
    test (count $tokens) -eq 3; and test "$tokens[3]" = "$current"
end


function __hz_top_command_is
    set -l tokens (commandline -opc)
    test (count $tokens) -ge 2; or return 1
    contains -- $tokens[2] $argv
end

function __hz_command_is
    set -l tokens (commandline -opc)
    test (count $tokens) -ge 2; or return 1

    set -l cmd $tokens[2]
    if contains -- $cmd worktree wt
        test (count $tokens) -ge 3; or return 1
        set cmd $tokens[3]
    end

    contains -- $cmd $argv
end



function __hz_current_repo_arg
    set -l tokens (commandline -opc)
    set -l count (count $tokens)
    test $count -gt 0; or return

    for index in (seq 1 $count)
        switch $tokens[$index]
            case -r --repo
                set -l next_index (math $index + 1)
                if test $next_index -le $count
                    echo $tokens[$next_index]
                    return
                end
            case '--repo=*'
                string replace -- '--repo=' '' $tokens[$index]
                return
        end
    end
end

function __hz_complete_git_refs
    set -l repo (__hz_current_repo_arg)
    if test -n "$repo"
        command git -C "$repo" for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null
    else
        command git for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null
    end
end

function __hz_previous_token
    set -l tokens (commandline -opc)
    set -l current (commandline -ct)
    set -l count (count $tokens)
    test $count -gt 0; or return

    if test "$tokens[$count]" = "$current"
        set count (math $count - 1)
    end
    test $count -gt 0; and echo $tokens[$count]
end

complete -c hz -e
complete -c hzcd -e
complete -c hzlocal -e

complete -c hz -f
complete -c hz -n "not __fish_seen_subcommand_from new fork path cd list ls remove rm handoff init install setup cleanup shell update worktree wt" -a "new fork path cd list ls remove rm handoff init install setup cleanup shell update worktree wt"
complete -c hz -n "__hz_needs_worktree_subcommand" -a "new fork path cd list ls remove rm handoff"

complete -c hz -n "__hz_command_is cd path handoff setup cleanup" -a "(__hz_complete_worktree_targets)"
complete -c hz -n "__hz_command_is rm remove" -a "(__hz_complete_removable_worktrees)"
complete -c hz -n "__hz_top_command_is init install shell" -a "zsh bash fish"
complete -c hz -n "__hz_command_is new fork path cd list ls remove rm handoff init setup cleanup" -s r -l repo -r -F
complete -c hz -n "__hz_command_is new fork" -s p -l path -r -F
complete -c hz -n "__hz_command_is new" -s B -l base -r -a "(__hz_complete_git_refs)"
complete -c hz -n "__hz_command_is new" -s b -l branch -r -a "(__hz_complete_git_refs)"
complete -c hz -n "__hz_command_is new fork handoff" -l max-detached -r
complete -c hz -n "__hz_command_is new handoff" -l max-branch-worktrees -r
complete -c hz -n "__hz_command_is new" -l no-setup
complete -c hz -n "__hz_command_is new" -l setup
complete -c hz -n "__hz_command_is fork" -l no-diff
complete -c hz -n "__hz_command_is new fork path cd list ls remove rm handoff" -s j -l json
complete -c hz -n "__hz_command_is new remove rm" -s d -l debug
complete -c hz -n "__hz_command_is remove rm" -s f -l force
complete -c hz -n "__hz_command_is remove rm" -l yes
complete -c hz -n "__hz_command_is remove rm" -l no-cleanup
complete -c hz -n "__hz_command_is remove rm" -l cleanup
complete -c hz -n "__hz_command_is handoff" -s b -l branch
complete -c hz -n "__hz_command_is handoff" -s n -l new
complete -c hz -n "__hz_top_command_is update" -l target-version -r
complete -c hz -n "__hz_top_command_is update" -l install-dir -r -F
complete -c hz -n "__hz_top_command_is update" -l force-self-update
complete -c hz -s h -l help

complete -c hzcd -f
complete -c hzcd -a "(__hz_complete_worktree_targets)"
complete -c hzcd -s r -l repo -r -F
complete -c hzcd -s j -l json
complete -c hzcd -s h -l help

complete -c hzlocal -f
complete -c hzlocal -s r -l repo -r -F
complete -c hzlocal -s j -l json
complete -c hzlocal -s h -l help
complete -c hz -n "not __fish_seen_subcommand_from new fork path cd list ls remove rm handoff init install setup cleanup shell update worktree wt" -s V -l version
