# Generated by `hz shell zsh`.

alias hz='noglob _hz'
alias hzcd='noglob _hzcd'
alias hzlocal='noglob _hzlocal'

_hz() {
  if [[ "$#" -eq 0 ]]; then
    command hz
    return
  fi

  local cmd="$1"
  case "$cmd" in
    new)
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--path-only|--help|-h|-j)
            command hz "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz "$@" --path-only)" || return
      builtin cd "$hz_target_path" || return
      ;;
    handoff)
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--path-only|--help|-h|-j)
            command hz "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz "$@" --path-only)" || return
      builtin cd "$hz_target_path" || return
      ;;
    cd)
      shift
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--path-only|--help|-h|-j)
            command hz "$cmd" "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz path "$@")" || return
      builtin cd "$hz_target_path" || return
      ;;
    *)
      command hz "$@"
      ;;
  esac
}

_hzcd() {
  _hz cd "$@"
}

_hzlocal() {
  _hz cd local "$@"
}

_hz_worktree_targets() {
  local -a targets
  targets=("${(@f)$(command hz __complete worktree-targets 2>/dev/null)}")
  compadd -a targets
}

_hz_removable_worktrees() {
  local -a targets
  targets=("${(@f)$(command hz __complete removable-worktrees 2>/dev/null)}")
  compadd -a targets
}

_hz_complete_main() {
  local -a commands
  commands=(
    'new:create a worktree'
    'path:print a worktree path'
    'cd:change to a worktree'
    'list:list worktrees'
    'ls:list worktrees'
    'remove:remove one or more worktrees'
    'rm:remove one or more worktrees'
    'handoff:apply changes between linked worktrees'
    'init:initialize hz repo config'
    'install:install shell integration'
    'setup:run worktree setup'
    'cleanup:run worktree cleanup'
    'shell:print shell integration'
    'update:update hz from GitHub releases'
    'diff:review a git diff'
    'worktree:worktree commands'
    'wt:worktree commands'
  )

  _describe -t commands 'hz command' commands
}

_hz_complete_worktree_subcommand() {
  local -a commands
  commands=(
    'new:create a worktree'
    'path:print a worktree path'
    'cd:change to a worktree'
    'list:list worktrees'
    'ls:list worktrees'
    'remove:remove one or more worktrees'
    'rm:remove one or more worktrees'
    'handoff:apply changes between linked worktrees'
  )

  _describe -t commands 'hz worktree command' commands
}

_hz_complete_shells() {
  compadd zsh bash fish
}

_hz_complete_option_value() {
  local cmd="$1"
  local previous="${words[$(( CURRENT - 1 ))]}"

  case "$previous" in
    -r|--repo)
      case "$cmd" in
        new|path|cd|list|ls|remove|rm|handoff|setup|cleanup|init|diff)
          _files -/
          return 0
          ;;
      esac
      ;;
    -p|--path)
      if [[ "$cmd" == "new" ]]; then
        _files -/
        return 0
      fi
      ;;
    -B|--base)
      case "$cmd" in
        new|diff)
          _message 'branch or revision'
          return 0
          ;;
      esac
      ;;
    -b|--branch)
      case "$cmd" in
        new|diff)
          _message 'branch'
          return 0
          ;;
      esac
      ;;
    --max-detached)
      case "$cmd" in
        new|handoff)
          _message 'count'
          return 0
          ;;
      esac
      ;;
    --target-version)
      if [[ "$cmd" == "update" ]]; then
        _message 'version'
        return 0
      fi
      ;;
    --install-dir)
      if [[ "$cmd" == "update" ]]; then
        _files -/
        return 0
      fi
      ;;
    --patch)
      if [[ "$cmd" == "diff" ]]; then
        _files
        return 0
      fi
      ;;
  esac

  return 1
}

_hz_complete_command_options() {
  local cmd="$1"

  case "$cmd" in
    new)
      compadd -- -r --repo -p --path -B --base -b --branch --max-detached -j --json -d --debug --no-setup -h --help
      ;;
    path|cd)
      compadd -- -r --repo -j --json -h --help
      ;;
    list|ls)
      compadd -- -r --repo -j --json -h --help
      ;;
    remove|rm)
      compadd -- -r --repo -j --json -f --force --yes -d --debug --no-cleanup -h --help
      ;;
    handoff)
      compadd -- -b --branch -n --new --max-detached -r --repo -j --json -h --help
      ;;
    setup|cleanup)
      compadd -- -r --repo -h --help
      ;;
    init)
      compadd -- -r --repo -h --help
      ;;
    install|shell)
      compadd -- -h --help
      ;;
    update)
      compadd -- --target-version --install-dir -h --help
      ;;
    diff)
      compadd -- -r --repo -b --base --staged --unstaged --no-untracked --patch -s --stat -h --help
      ;;
  esac
}

_hz_complete_command_positionals() {
  local cmd="$1"

  case "$cmd" in
    path|cd)
      _arguments \
        '1:worktree target:_hz_worktree_targets'
      ;;
    remove|rm)
      _arguments \
        '*:worktree targets:_hz_removable_worktrees'
      ;;
    handoff|setup|cleanup)
      _arguments \
        '1:worktree target:_hz_worktree_targets'
      ;;
    init|install|shell)
      _arguments \
        '1:shell:_hz_complete_shells'
      ;;
  esac
}

_hz_complete_command_args() {
  local cmd="$1"

  if _hz_complete_option_value "$cmd"; then
    return
  fi

  if [[ "$PREFIX" == -* ]]; then
    _hz_complete_command_options "$cmd"
    return
  fi

  _hz_complete_command_positionals "$cmd"
}

_hz_completion() {
  if (( CURRENT == 2 )); then
    if [[ "$PREFIX" == -* ]]; then
      compadd -- -h --help -V --version
      return
    fi
    _hz_complete_main
    return
  fi

  local cmd="${words[2]}"
  if [[ "$cmd" == "worktree" || "$cmd" == "wt" ]]; then
    if (( CURRENT == 3 )); then
      _hz_complete_worktree_subcommand
      return
    fi
    local subcmd="${words[3]}"
    shift 2 words
    (( CURRENT -= 2 ))
    _hz_complete_command_args "$subcmd"
    return
  fi

  shift words
  (( CURRENT-- ))
  _hz_complete_command_args "$cmd"
}

_hzcd_completion() {
  if _hz_complete_option_value cd; then
    return
  fi

  if [[ "$PREFIX" == -* ]]; then
    _hz_complete_command_options cd
    return
  fi

  _hz_complete_command_positionals cd
}

_hzlocal_completion() {
  if _hz_complete_option_value cd; then
    return
  fi

  if [[ "$PREFIX" == -* ]]; then
    _hz_complete_command_options cd
    return
  fi

  return 0
}

_hz_register_completion() {
  if ! (( $+functions[compdef] )); then
    autoload -Uz compinit
    compinit -C
  fi

  if (( $+functions[compdef] )); then
    compdef _hz_completion hz _hz
    compdef _hzcd_completion hzcd _hzcd
    compdef _hzlocal_completion hzlocal _hzlocal
  fi
}

_hz_register_completion
unfunction _hz_register_completion
