# Generated by `hz shell zsh`.

alias hz='noglob _hz'
alias hzcd='noglob _hzcd'
alias hzlocal='noglob _hzlocal'

_hz() {
  if [[ "$#" -eq 0 ]]; then
    command hz
    return
  fi

  local cmd="$1"
  case "$cmd" in
    new|fork)
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--machine|--path-only|--help|-h|-j)
            command hz "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz "$@" --path-only)" || return
      builtin cd "$hz_target_path" || return
      ;;
    handoff)
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--machine|--path-only|--help|-h|-j)
            command hz "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz "$@" --path-only)" || return
      builtin cd "$hz_target_path" || return
      ;;
    cd)
      shift
      local arg
      for arg in "$@"; do
        case "$arg" in
          --json|--machine|--path-only|--help|-h|-j)
            command hz "$cmd" "$@"
            return
            ;;
        esac
      done

      local hz_target_path
      hz_target_path="$(command hz path "$@")" || return
      builtin cd "$hz_target_path" || return
      ;;
    *)
      command hz "$@"
      ;;
  esac
}

_hzcd() {
  _hz cd "$@"
}

_hzlocal() {
  _hz cd local "$@"
}

_hz_worktree_targets() {
  local repo
  local -a complete_args
  repo="$(_hz_current_repo_arg)"
  if [[ -n "$repo" ]]; then
    complete_args=(-r "$repo")
  fi

  local -a targets
  targets=("${(@f)$(command hz __complete worktree-targets "${complete_args[@]}" 2>/dev/null)}")
  compadd -a targets
}

_hz_removable_worktrees() {
  local repo
  local -a complete_args
  repo="$(_hz_current_repo_arg)"
  if [[ -n "$repo" ]]; then
    complete_args=(-r "$repo")
  fi

  local -a targets
  targets=("${(@f)$(command hz __complete removable-worktrees "${complete_args[@]}" 2>/dev/null)}")
  compadd -a targets
}

_hz_current_repo_arg() {
  local index word
  for (( index = 2; index < CURRENT; index++ )); do
    word="${words[$index]}"
    case "$word" in
      -r|--repo)
        if (( index + 1 < CURRENT )); then
          print -r -- "${words[$(( index + 1 ))]}"
          return
        fi
        ;;
      --repo=*)
        print -r -- "${word#--repo=}"
        return
        ;;
    esac
  done
}

_hz_git_refs() {
  local repo
  local -a refs
  repo="$(_hz_current_repo_arg)"
  if [[ -n "$repo" ]]; then
    refs=("${(@f)$(command git -C "$repo" for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null)}")
  else
    refs=("${(@f)$(command git for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null)}")
  fi
  compadd -a refs
}

_hz_complete_main() {
  local -a commands
  commands=(
    'new:create a worktree'
    'fork:fork the current worktree state'
    'path:print a worktree path'
    'cd:change to a worktree'
    'list:list worktrees'
    'ls:list worktrees'
    'pwd:print the current worktree target'
    'remove:remove one or more worktrees'
    'rm:remove one or more worktrees'
    'pin:pin worktrees'
    'unpin:unpin worktrees'
    'handoff:apply changes between linked worktrees'
    'init:initialize hz repo config'
    'install:install shell integration'
    'setup:run worktree setup'
    'cleanup:run worktree cleanup'
    'shell:print shell integration'
    'update:update hz from GitHub releases'
    'worktree:worktree commands'
    'wt:worktree commands'
  )

  _describe -t commands 'hz command' commands
}

_hz_complete_agent_subcommand() {
  local -a commands
  commands=(
    'new:create a worktree and print JSON'
    'fork:fork the current worktree state and print JSON'
    'path:print a worktree path as JSON'
    'cd:print a worktree path as JSON'
    'list:list worktrees as JSON'
    'ls:list worktrees as JSON'
    'pwd:print the current worktree as JSON'
    'current:print the current worktree as JSON'
    'remove:remove worktrees and print a JSON array'
    'rm:remove worktrees and print a JSON array'
    'pin:pin worktrees and print JSON'
    'unpin:unpin worktrees and print JSON'
    'handoff:apply changes between linked worktrees and print JSON'
    'setup:run setup lifecycle and print JSON'
    'cleanup:run cleanup lifecycle and print JSON'
  )

  _describe -t commands 'hz agent command' commands
}


_hz_complete_worktree_subcommand() {
  local -a commands
  commands=(
    'new:create a worktree'
    'fork:fork the current worktree state'
    'path:print a worktree path'
    'cd:change to a worktree'
    'list:list worktrees'
    'ls:list worktrees'
    'pwd:print the current worktree target'
    'remove:remove one or more worktrees'
    'rm:remove one or more worktrees'
    'pin:pin worktrees'
    'unpin:unpin worktrees'
    'handoff:apply changes between linked worktrees'
  )

  _describe -t commands 'hz worktree command' commands
}


_hz_complete_shells() {
  compadd zsh bash fish
}

_hz_is_global_flag() {
  case "$1" in
    --machine|-h|--help|-V|--version)
      return 0
      ;;
  esac
  return 1
}

_hz_command_word_index() {
  local index word
  for (( index = 2; index < CURRENT; index++ )); do
    word="${words[$index]}"
    if _hz_is_global_flag "$word"; then
      continue
    fi
    print -r -- "$index"
    return 0
  done
  return 1
}

_hz_subcommand_word_index() {
  local command_index="$1"
  local index word
  for (( index = command_index + 1; index < CURRENT; index++ )); do
    word="${words[$index]}"
    if _hz_is_global_flag "$word"; then
      continue
    fi
    print -r -- "$index"
    return 0
  done
  return 1
}

_hz_complete_option_value() {
  local cmd="$1"
  local previous="${words[$(( CURRENT - 1 ))]}"

  case "$previous" in
    -r|--repo)
      case "$cmd" in
        new|fork|path|cd|list|ls|pwd|current|remove|rm|pin|unpin|handoff|setup|cleanup|init)
          _files -/
          return 0
          ;;
      esac
      ;;
    -p|--path)
      if [[ "$cmd" == "new" || "$cmd" == "fork" ]]; then
        _files -/
        return 0
      fi
      ;;
    -B)
      case "$cmd" in
        new)
          _hz_git_refs
          return 0
          ;;
      esac
      ;;
    -b)
      case "$cmd" in
        new)
          _hz_git_refs
          return 0
          ;;
      esac
      ;;
    --base)
      case "$cmd" in
        new)
          _hz_git_refs
          return 0
          ;;
      esac
      ;;
    --branch)
      case "$cmd" in
        new)
          _hz_git_refs
          return 0
          ;;
      esac
      ;;
    --max-detached)
      case "$cmd" in
        new|fork|handoff)
          _message 'count'
          return 0
          ;;
      esac
      ;;
    --max-branch-worktrees)
      case "$cmd" in
        new|handoff)
          _message 'count'
          return 0
          ;;
      esac
      ;;
    --target-version)
      if [[ "$cmd" == "update" ]]; then
        _message 'version'
        return 0
      fi
      ;;
    --install-dir)
      if [[ "$cmd" == "update" ]]; then
        _files -/
        return 0
      fi
      ;;
  esac

  return 1
}

_hz_complete_command_options() {
  local cmd="$1"

  case "$cmd" in
    new)
      compadd -- -r --repo -p --path -B --base -b --branch --max-detached --max-branch-worktrees -j --json -d --debug --setup --no-setup --machine -h --help
      ;;
    fork)
      compadd -- -r --repo -p --path --no-diff --max-detached -j --json --machine -h --help
      ;;
    path|cd)
      compadd -- -r --repo -j --json --machine -h --help
      ;;
    list|ls)
      compadd -- -r --repo --pinned --unpinned -j --json --machine -h --help
      ;;
    pwd|current)
      compadd -- -r --repo -j --json --machine -h --help
      ;;
    remove|rm)
      compadd -- -r --repo -j --json -f --force --yes -d --debug --cleanup --no-cleanup --machine -h --help
      ;;
    pin|unpin)
      compadd -- -r --repo -j --json --machine -h --help
      ;;
    handoff)
      compadd -- -b --branch -n --new --max-detached --max-branch-worktrees -r --repo -j --json --machine -h --help
      ;;
    setup|cleanup)
      compadd -- -r --repo -j --json --machine -h --help
      ;;
    init)
      compadd -- -r --repo --machine -h --help
      ;;
    install|shell)
      compadd -- --machine -h --help
      ;;
    update)
      compadd -- --target-version --install-dir --machine -h --help
      ;;
  esac
}


_hz_complete_command_positionals() {
  local cmd="$1"

  case "$cmd" in
    path|cd)
      _arguments \
        '1:worktree target:_hz_worktree_targets'
      ;;
    remove|rm|pin|unpin)
      _arguments \
        '*:worktree targets:_hz_removable_worktrees'
      ;;
    handoff|setup|cleanup)
      _arguments \
        '1:worktree target:_hz_worktree_targets'
      ;;
    init|install|shell)
      _arguments \
        '1:shell:_hz_complete_shells'
      ;;
  esac
}

_hz_complete_command_args() {
  local cmd="$1"

  if _hz_complete_option_value "$cmd"; then
    return
  fi

  if [[ "$PREFIX" == -* ]]; then
    _hz_complete_command_options "$cmd"
    return
  fi

  _hz_complete_command_positionals "$cmd"
}

_hz_completion() {
  local cmd_index
  cmd_index="$(_hz_command_word_index)"
  if [[ -z "$cmd_index" ]]; then
    if [[ "$PREFIX" == -* ]]; then
      compadd -- --machine -h --help -V --version
      return
    fi
    _hz_complete_main
    return
  fi

  local cmd="${words[$cmd_index]}"
  if [[ "$cmd" == "worktree" || "$cmd" == "wt" || "$cmd" == "agent" ]]; then
    local subcmd_index
    subcmd_index="$(_hz_subcommand_word_index "$cmd_index")"
    if [[ -z "$subcmd_index" ]]; then
      if [[ "$PREFIX" == -* ]]; then
        compadd -- --machine -h --help
      elif [[ "$cmd" == "agent" ]]; then
        _hz_complete_agent_subcommand
      else
        _hz_complete_worktree_subcommand
      fi
      return
    fi
    local subcmd="${words[$subcmd_index]}"
    shift $(( subcmd_index - 1 )) words
    (( CURRENT -= subcmd_index - 1 ))
    _hz_complete_command_args "$subcmd"
    return
  fi


  shift $(( cmd_index - 1 )) words
  (( CURRENT -= cmd_index - 1 ))
  _hz_complete_command_args "$cmd"
}

_hzcd_completion() {
  if _hz_complete_option_value cd; then
    return
  fi

  if [[ "$PREFIX" == -* ]]; then
    _hz_complete_command_options cd
    return
  fi

  _hz_complete_command_positionals cd
}

_hzlocal_completion() {
  if _hz_complete_option_value cd; then
    return
  fi

  if [[ "$PREFIX" == -* ]]; then
    _hz_complete_command_options cd
    return
  fi

  return 0
}

_hz_register_completion() {
  if ! (( $+functions[compdef] )); then
    autoload -Uz compinit
    compinit -C
  fi

  if (( $+functions[compdef] )); then
    compdef _hz_completion hz _hz
    compdef _hzcd_completion hzcd _hzcd
    compdef _hzlocal_completion hzlocal _hzlocal
  fi
}

_hz_deferred_register_completion() {
  _hz_register_completion

  if (( $+functions[add-zsh-hook] )); then
    add-zsh-hook -d precmd _hz_deferred_register_completion
  fi

  unfunction _hz_deferred_register_completion
  unfunction _hz_register_completion
}

_hz_register_completion

if ! (( $+functions[add-zsh-hook] )); then
  autoload -Uz add-zsh-hook
fi

if (( $+functions[add-zsh-hook] )); then
  add-zsh-hook precmd _hz_deferred_register_completion
fi
